In [1]:
import numpy as np
import matplotlib as mpl
#mpl.use('pdf')
import matplotlib.pyplot as plt
import numpy as np

plt.rc('font', family='serif', serif='Times')
plt.rc('text', usetex=True)
plt.rc('xtick', labelsize=6)
plt.rc('ytick', labelsize=6)
plt.rc('axes', labelsize=6)
#axes.linewidth : 0.5
plt.rc('axes', linewidth=0.5)
#ytick.major.width : 0.5
plt.rc('ytick.major', width=0.5)
plt.rcParams['xtick.direction'] = 'in'
plt.rcParams['ytick.direction'] = 'in'
plt.rc('ytick.minor', visible=True)

#plt.style.use(r"..\..\styles\infocom.mplstyle") # Insert your save location here

# width as measured in inkscape
fig_width = 3.487
#height = width / 1.618 / 2
fig_height = fig_width / 1.3 / 2

In [2]:
cc_folder_list = ["SF_new_results/", "capacity_results/", "BF_new_results/"]
nc_folder_list = ["SF_new_results_NC/", "capacity_resultsNC/", "BF_new_results_NC/"]
cc_folder_list = ["failure20stages-new-rounding-capacity/" + e  for e in cc_folder_list]
nc_folder_list = ["failure20stages-new-rounding-capacity/" + e for e in nc_folder_list]
file_list = ["no-reconfig120.csv", "Link-reconfig120.csv", "LimitedReconfig120.csv", "Any-reconfig120.csv"]
print(cc_folder_list)
print(nc_folder_list)

['failure20stages-new-rounding-capacity/SF_new_results/', 'failure20stages-new-rounding-capacity/capacity_results/', 'failure20stages-new-rounding-capacity/BF_new_results/']
['failure20stages-new-rounding-capacity/SF_new_results_NC/', 'failure20stages-new-rounding-capacity/capacity_resultsNC/', 'failure20stages-new-rounding-capacity/BF_new_results_NC/']


In [3]:
nc_objective_data = np.full((5, 3), 0)
max_stage = 20
selected_stage = 10
for i in range(3):
    for j in range(4):
        with open(nc_folder_list[i]+file_list[j], "r") as f:
            if j != 2:
                f1 = f.readlines()
                start_line = 0
                for line in f1:
                    if line.find("%Stage") >= 0:
                        break
                    else:
                        start_line = start_line + 1
                #print(start_line)
                #print(len(f1))
                line = f1[selected_stage+start_line]
                line = line.split(",")
                if j == 0:
                    nc_objective_data[0, i] = float(line[2])
                if j == 1:
                    nc_objective_data[1, i] = float(line[2])
                if j == 3:
                    nc_objective_data[4, i] = float(line[2])
            else:
                f1 = f.readlines()
                start_line = 0
                start_line1 = 0
                for line in f1:
                    if line.find("%Stage") >= 0:
                        break
                    else:
                        start_line = start_line + 1
                for index in range(start_line+max_stage+1, len(f1)):
                    if f1[index].find("%Stage") >= 0:
                        start_line1 = index
                        break
                    else:
                        start_line1 = start_line1 + 1

                line = f1[selected_stage+start_line]
                line = line.split(",")
                nc_objective_data[2, i] = float(line[2])
                #mesh3data[2, index] = int(line[1])

                line = f1[selected_stage+start_line1]
                line = line.split(",")
                nc_objective_data[3, i] = float(line[2])
print(nc_objective_data)

[[3612 2447 1370]
 [4293 3338 2362]
 [4989 4581 3617]
 [5130 4762 3743]
 [5850 5796 4467]]


In [10]:
cc_objective_data = np.full((5, 3), 0)
max_stage = 20
selected_stage = 10
for i in range(1):
    for j in range(4):
        with open(cc_folder_list[i]+file_list[j], "r") as f:
            if j != 2:
                f1 = f.readlines()
                start_line = 0
                for line in f1:
                    if line.find("%Stage") >= 0:
                        break
                    else:
                        start_line = start_line + 1
                #print(start_line)
                #print(len(f1))
                line = f1[selected_stage+start_line]
                line = line.split(",")
                if j == 0:
                    cc_objective_data[0, i] = float(line[2])
                if j == 1:
                    cc_objective_data[1, i] = float(line[2])
                if j == 3:
                    cc_objective_data[4, i] = float(line[2])
            else:
                f1 = f.readlines()
                start_line = 0
                start_line1 = 0
                for line in f1:
                    if line.find("%Stage") >= 0:
                        break
                    else:
                        start_line = start_line + 1
                for index in range(start_line+max_stage+1, len(f1)):
                    if f1[index].find("%Stage") >= 0:
                        print(f1[index])
                        start_line1 = index
                        break
                    else:
                        start_line1 = start_line1 + 1

                line = f1[selected_stage+start_line]
                line = line.split(",")
                cc_objective_data[2, i] = float(line[2])
                #mesh3data[2, index] = int(line[1])

                line = f1[selected_stage+start_line1]
                line = line.split(",")
                cc_objective_data[3, i] = float(line[2])
print(cc_objective_data)

%Stage 0, 281, 281,342, 306, 0.15, 0.16279069767441862

[[3640    0    0]
 [4424    0    0]
 [5122    0    0]
 [5145    0    0]
 [5966    0    0]]


In [12]:
max_stage = 20
selected_stage = 10
for i in range(1, 3):
    for j in range(4):
        with open(cc_folder_list[i]+file_list[j], "r") as f:
            if j != 2:
                f1 = f.readlines()
                start_line = 0
                for line in f1:
                    if line.find("%Stage") >= 0:
                        break
                    else:
                        start_line = start_line + 1
                #print(start_line)
                #print(len(f1))
                line = f1[selected_stage+start_line]
                line = line.split(",")
                if j == 0:
                    cc_objective_data[0, i] = float(line[2])
                if j == 1:
                    cc_objective_data[1, i] = float(line[2])
                if j == 3:
                    cc_objective_data[4, i] = float(line[2])
            else:
                f1 = f.readlines()
                start_line = 0
                start_line1 = 0
                for line in f1:
                    if line.find("%Stage") >= 0:
                        break
                    else:
                        start_line = start_line + 1
                for index in range(start_line+max_stage+1, len(f1)):
                    if f1[index].find("%Stage") >= 0:
                        start_line1 = index
                        break
                    else:
                        start_line1 = start_line1 + 1

                line = f1[selected_stage+start_line]
                line = line.split(",")
                cc_objective_data[2, i] = float(line[2])
                #mesh3data[2, index] = int(line[1])

                line = f1[selected_stage+start_line1]
                line = line.split(",")
                cc_objective_data[3, i] = float(line[2])
print(cc_objective_data)

[[3640 2507 1378]
 [4424 3618 2454]
 [5122 4723 3754]
 [5145 4804 3835]
 [5966 5995 4273]]


In [13]:
print((cc_objective_data-nc_objective_data)/nc_objective_data)

[[ 0.00775194  0.02451982  0.00583942]
 [ 0.03051479  0.08388256  0.03895004]
 [ 0.02665865  0.0309976   0.03787669]
 [ 0.00292398  0.00881982  0.02457921]
 [ 0.01982906  0.03433402 -0.04342959]]


In [ ]:
import numpy as np
N = 3
ind = np.arange(N) 
width = 1 / 6

x = [0, '20', '30', '40']
x_tick_label_list = ['20', '30', '40']

fig, (ax1, ax2) = plt.subplots(1, 2)
#ax1.bar(x, objective)
#ax1.bar(x, objective[0])
label_list = ['No-rec', 'Link-rec', 'Lim-rec(3, 0)', 'Lim-rec(3, 1)', 'Any-rec']
patterns = ('//////','\\\\\\','---',  'ooo', 'xxx', '\\', '\\\\','++', '*', 'O', '.')

plt.rcParams['hatch.linewidth'] = 0.25  # previous pdf hatch linewidth
#plt.rcParams['hatch.linewidth'] = 1.0  # previous svg hatch linewidth
#plt.rcParams['hatch.color'] = 'r'

for i in range(5):
    ax1.bar(ind + width * (i-2), nc_objective_data[i], width, label=label_list[i],
            #alpha=0.7)
           hatch=patterns[i], alpha=0.7)
           #yerr=error[i], ecolor='black', capsize=1)
ax1.grid(lw = 0.25)
ax2.grid(lw = 0.25)

ax1.set_xticklabels(x)
ax1.set_ylabel('Objective value for NC')
ax1.set_xlabel('Percentage of substrate failures (\%)')
#ax1.set_ylabel('Objective value')
#ax1.set_xlabel('Recovery Scenarios')
ax1.xaxis.set_label_coords(0.5,-0.17)
ax1.yaxis.set_label_coords(-0.17,0.5)

#ax1.legend(loc='upper center', bbox_to_anchor=(0.5, 1.05),
#          ncol=3, fancybox=True, shadow=True, fontsize='small')

for i in range(5):
    ax2.bar(ind + width * (i-2), cc_objective_data[i], width, label=label_list[i],
            #alpha=0.7)
           hatch=patterns[i], alpha=0.7)

ax2.set_xticklabels(x)
ax2.set_ylabel('Objective value for CC')
ax2.set_xlabel('Percentage of substrate failures (\%)')
ax2.xaxis.set_label_coords(0.5,-0.17)
ax2.yaxis.set_label_coords(-0.17,0.5)

ax1.legend(loc='upper center', bbox_to_anchor=(1.16, 1.2),
          ncol=5, prop={'size': 5})

fig.set_size_inches(fig_width, fig_height)
mpl.pyplot.subplots_adjust(wspace = 0.3)

fig.subplots_adjust(left=.10, bottom=.20, right=.97, top=.85)
#ax1.grid(color='b', ls = '-.', lw = 0.25)



plt.show()
fig.savefig('test-heuristic-failure-cc-nc.pdf')